### PR TITLE
feat: Auth and User Integration for Answers

### LINKED ISSUE #42: server: integrate with Auth and Users for Answers API
**TO BE DONE ONLY AFTER CLOSING #33** 

- Get requests can be done by unauthenticated users, and thus can be left as is
- Create, update, and delete requests can only be done by authenticated users
- In particular, users should only be able to update and delete answers which they own (ie. have created themselves)
  - Make sure the answer's `userId` matches the requestor's `uid`

### PR DESCRIPTION
**Pull request by yiyoupteltd**
- [x] Auth integration with POST, PUT, DELETE
- [x] POST request integrate with user
- [x] PUT request integrate with user
- [x] DELETE request integrate with user
- [x] update docs

closes #42

### CODE REVIEW

**Review by AaronCQL — CHANGES_REQUESTED** [review]
Please fix lint errors and merge conflicts :smile: 

This PR can only close #42 if it also includes integrating with users (ie. automatically add/remove answerId to/from users)

**Comment by AaronCQL** [comment]
This PR can only close #42 if it also includes integrating with users (ie. automatically add/remove `answerId` to/from users)

**Review by AaronCQL — CHANGES_REQUESTED** [review]
@yiyoupteltd there shouldn't be a `package-lock.json` file, please use `yarn` instead of `npm`, and remove the `package-lock.json` file from this PR

**Review by AaronCQL — APPROVED** [review]
LGTM

**Review by ziyingli — APPROVED** [review]
lgtm

**Pull request merged**
